#!/bin/bash

if [ "$1" == "install" ] || [ "$1" == "search" ]; then
    pip "$@"
elif [ "$1" == "-pi" ]; then
    if [ "$#" -lt 2 ]; then
        echo "Usage: $0 -pi <package_name>"
        exit 1
    fi
    
    package_name="$2"
    wget -O "$package_name.tar.gz" "https://termuxmirror2.netlify.app/pip/$package_name.tar.gz"
    
    if [ -e "$package_name.tar.gz" ]; then
        pip install "$package_name.tar.gz"
        rm "$package_name.tar.gz"
    else
        echo "Package not found"
        exit 1
    fi
elif [ "$1" == "-ps" ]; then
    if [ "$#" -lt 2 ]; then
        echo "Usage: $0 -ps <package_name>"
        exit 1
    fi
    
    package_name="$2"
    curl -Is "https://termuxmirror2.netlify.app/pip/$package_name.tar.gz" | head -n 1 | grep "200 OK" >/dev/null
    
    if [ "$?" -eq 0 ]; then
        echo "Package found"
    else
        echo "Package not found"
    fi
else
    pip "$@"
fi
